# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-waste-predictor-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food-waste-predictor
  template:
    metadata:
      labels:
        app: food-waste-predictor
    spec:
      containers:
      - name: app
        image: $(imageTag) # This placeholder is replaced by GitHub Actions
        ports:
        - containerPort: 8080